### ISSUE TITLE
Tests are flakey 

### ISSUE THREAD

**Issue by sublimator** [interledgerjs/interledgerjs#305]
Seem to require rerunning now and then
Can perhaps set it to retry a number of times

**Comment by sublimator** [comment]
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/525211/217146393-ebca41ed-a44f-4322-81bf-ac9bde805b24.png">

```
ilp-protocol-stream:   1 failing
ilp-protocol-stream:   1) Connection
ilp-protocol-stream:        Closing Streams
ilp-protocol-stream:          should remove the stream record when it is closed:
ilp-protocol-stream:      Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/interledgerjs/interledgerjs/packages/ilp-protocol-stream/test/connection.spec.ts)
ilp-protocol-stream:       at listOnTimeout (internal/timers.js:557:17)
ilp-protocol-stream:       at processTimers (internal/timers.js:500:7)
ilp-protocol-stream: 
ilp-protocol-stream: error Command failed with exit code 1.
ilp-protocol-stream: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sublimator** [comment]
Retrying via #338 should do the trick for the most part
